### PR TITLE
Fix missing name for models when loading some rmv2 files for Pharao  #137

### LINKED ISSUE #137: Total War Pharaoh model names will not load the object names
When opening any pharaoh model, the name of the object will not be shown. For example, if the rigid model is named phar_sea_tunic_03.rigidmodel, when you double click it, inside the model view the object will not have a name unless you manually add the name. This can lead to issues with wsmodel generation if the user does not put the name in.

### PR DESCRIPTION
**Pull request by HorseF3thers**
Object names now populate properly, this results in proper wsModel generation.

### CODE REVIEW

File: GameWorld/View3D/SceneNodes/Rmv2ModelNodeLoader.cs [hunk 1]
```diff
@@ -46,6 +46,22 @@ public void CreateModelNodesFromFile(Rmv2ModelNode outputNode, RmvFile model, An
                 {
                     var geometry = MeshBuilderService.BuildMeshFromRmvModel(model.ModelList[lodIndex][modelIndex], model.Header.SkeletonName, _contextFactory.Create());
                     var rmvModel = model.ModelList[lodIndex][modelIndex];
+
```
Comment (donkeyProgramming) [inline GameWorld/View3D/SceneNodes/Rmv2ModelNodeLoader.cs:49]: when looking for empty string, prefer using string.IsNullOrWhiteSpace as it covers more cases. Typically you want to cover them all when you are doing == "".

File: GameWorld/View3D/SceneNodes/Rmv2ModelNodeLoader.cs [hunk 2]
```diff
@@ -46,6 +46,22 @@ public void CreateModelNodesFromFile(Rmv2ModelNode outputNode, RmvFile model, An
...
+                    //This if statement is for Pharaoh Total War, the base game models do not have a model name by default so I am grabbing it
+                    //from the model file path.
+                    if (rmvModel.Material.ModelName == "")
+                    {
+                        string[] parts = modelFullPath.Split('\\');
+                        if (parts.Length >= 2)
+                        {
+                            rmvModel.Material.ModelName = parts[parts.Length - 2];
+                        }
+                        else
```
Comment (donkeyProgramming) [inline GameWorld/View3D/SceneNodes/Rmv2ModelNodeLoader.cs:59]: Consider using Path.GetFileName as is would simplify this code.

File: GameWorld/View3D/Services/SceneSaving/Material/Strategies/WsModelGeneratorService.cs [hunk 3]
```diff
@@ -105,6 +105,22 @@ private List<string> GenerateUniqueNames(List<Rmv2MeshNode> meshes)
             foreach (var mesh in meshes)
             {
                 var fileName = mesh.Name;
+                var modelFullPath = mesh.OriginalFilePath;
+                //if mesh name is blank, grab a mesh name from the file path, so far the only
+                //total war with this issue appears to be Pharaoh.
+                if (fileName == "")
+                {
```
Comment (donkeyProgramming) [inline GameWorld/View3D/Services/SceneSaving/Material/Strategies/WsModelGeneratorService.cs:112]: Same as above.

File: GameWorld/View3D/SceneNodes/Rmv2MeshNode.cs [hunk 4]
```diff
@@ -69,7 +69,7 @@ void UpdateMatrix()
         private Rmv2MeshNode()
         { }
 
-        public Rmv2MeshNode(RmvCommonHeader commonHeader, MeshObject meshObject, IMaterial material, AnimationPlayer animationPlayer, RenderEngineComponent renderEngineComponent, PbrShader shader = null)
+        public Rmv2MeshNode(RmvCommonHeader commonHeader, MeshObject meshObject, IMaterial material, AnimationPlayer animationPlayer, RenderEngineComponent renderEngineComponent, PbrShader shader = null )
```
Comment (donkeyProgramming) [inline GameWorld/View3D/SceneNodes/Rmv2MeshNode.cs:72]: When possible, try to undo changes to files that you have edited but later changes. 
This should ideally not be part of the PR as it takes time and focus away from actual changes. 
Dont worry about it, just a note for later

**Review by donkeyProgramming — CHANGES_REQUESTED** [review]
